"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_tags_name_lower', 'tags', [sa.text('lower(name)')], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    
    op.create_table('videos',
    sa.Column('id', sa.String(length=11), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_created_at', 'videos', ['created_at'], unique=False)
    op.create_index('ix_videos_title_lower', 'videos', [sa.text('lower(title)')], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('client_note_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp_sec', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_client_id', 'notes', ['video_id', 'client_note_id'], unique=True)
    op.create_index('ix_notes_video_timestamp', 'notes', ['video_id', 'timestamp_sec'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    
    op.create_table('video_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_tags_unique', 'video_tags', ['video_id', 'tag_id'], unique=True)
    op.create_index(op.f('ix_video_tags_id'), 'video_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_tags_id'), table_name='video_tags')
    op.drop_index('ix_video_tags_unique', table_name='video_tags')
    op.drop_table('video_tags')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index('ix_notes_video_timestamp', table_name='notes')
    op.drop_index('ix_notes_client_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index('ix_videos_title_lower', table_name='videos')
    op.drop_index('ix_videos_created_at', table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('ix_tags_name_lower', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###